import "./globals.css";
import type {Metadata} from "next";
import AuthProvider from "../../provider/AuthProvider";


export const metadata: Metadata = {
    title: "سازمان ملی استاندارد",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fa">
        <body>
        {/*<StyledComponentsRegistry>*/}
        {/*<ConfigProvider direction="rtl" theme={theme} locale={fa_IR}>*/}
        <AuthProvider>
            {children}
        </AuthProvider>
        {/*</ConfigProvider>*/}
        {/*</StyledComponentsRegistry>*/}
        </body>
        </html>
    );
}
