import "./globals.css";
import type {Metadata} from "next";
import AuthProvider from "../../provider/authProvider";


export const metadata: Metadata = {
    title: "سازمان ملی استاندارد",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fa">
        <body>
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
